#!/usr/bin/env node
/**
 * Frontend Guardian — interactive setup CLI
 * Run with:  npx frontend-guardian@latest init
 */

import { execSync, spawnSync } from "child_process";
import { randomBytes }         from "crypto";
import { existsSync, writeFileSync, readFileSync } from "fs";
import { join }                from "path";
import * as readline           from "readline";

// ─── Colours ──────────────────────────────────────────────────────────────────

const c = {
  reset:  "\x1b[0m",
  bold:   "\x1b[1m",
  green:  "\x1b[32m",
  yellow: "\x1b[33m",
  cyan:   "\x1b[36m",
  red:    "\x1b[31m",
  grey:   "\x1b[90m",
  blue:   "\x1b[34m",
};

const ok   = (msg: string) => console.log(`${c.green}✓${c.reset}  ${msg}`);
const info = (msg: string) => console.log(`${c.cyan}ℹ${c.reset}  ${msg}`);
const warn = (msg: string) => console.log(`${c.yellow}⚠${c.reset}  ${msg}`);
const err  = (msg: string) => console.log(`${c.red}✗${c.reset}  ${msg}`);
const step = (n: number, msg: string) =>
  console.log(`\n${c.bold}${c.blue}[${n}/5]${c.reset} ${c.bold}${msg}${c.reset}`);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ask(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => { rl.close(); resolve(answer.trim()); });
  });
}

function run(cmd: string, opts: { silent?: boolean } = {}): boolean {
  const result = spawnSync(cmd, { shell: true, stdio: opts.silent ? "pipe" : "inherit" });
  return result.status === 0;
}

function hasCommand(cmd: string): boolean {
  return run(`command -v ${cmd}`, { silent: true });
}

// ─── Content generators ───────────────────────────────────────────────────────

function makeDockerCompose(port: number): string {
  return `version: "3.9"
services:
  guardian-server:
    image: node:20-alpine
    container_name: guardian-server
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install -g @frontend-guardian/server 2>/dev/null; npx @frontend-guardian/server"
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: "4000"
    ports:
      - "4000:4000"
    volumes:
      - guardian-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  guardian-dashboard:
    image: nginx:alpine
    container_name: guardian-dashboard
    restart: unless-stopped
    ports:
      - "${port}:80"
    depends_on:
      guardian-server:
        condition: service_healthy

volumes:
  guardian-data:
`;
}

function makeEnvFile(apiKey: string): string {
  return `# Frontend Guardian — generated by npx frontend-guardian init
GUARDIAN_API_KEY=${apiKey}
PORT=4000
MAX_EVENTS=50000
MAX_ANALYSES=25000
RULE_WINDOW=200
AI_ENABLED=false
AI_PROVIDER=none
AI_API_KEY=
ALERT_SLACK_WEBHOOK=
ALERT_WEBHOOK_URL=
ALERT_MIN_SEVERITY=error
DASHBOARD_URL=http://localhost:3000
DB_PATH=/app/data/guardian.db
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log(`
${c.bold}${c.blue}  🛡️  Frontend Guardian — Setup${c.reset}
${c.grey}  AI-powered frontend monitoring${c.reset}
`);

  const cwd = process.cwd();

  // ── Step 1: Check Docker ──────────────────────────────────────────────────

  step(1, "Checking Docker");

  if (!hasCommand("docker")) {
    err("Docker is not installed.");
    info("Install Docker Desktop from https://www.docker.com/products/docker-desktop");
    process.exit(1);
  }

  if (!run("docker info", { silent: true })) {
    err("Docker is installed but not running.");
    info("Please start Docker Desktop and try again.");
    process.exit(1);
  }

  ok("Docker is running");

  // ── Step 2: Choose install directory ─────────────────────────────────────

  step(2, "Install location");

  const defaultDir = join(cwd, "guardian");
  const dirAnswer  = await ask(
    `  ${c.grey}Install in (press Enter for ${defaultDir}):${c.reset} `
  );
  const installDir = dirAnswer || defaultDir;

  if (!existsSync(installDir)) {
    run(`mkdir -p "${installDir}"`);
    ok(`Created directory: ${installDir}`);
  } else {
    ok(`Using directory: ${installDir}`);
  }

  // ── Step 3: Generate API key ──────────────────────────────────────────────

  step(3, "Generating API key");

  const envPath = join(installDir, ".env");
  let   apiKey  = "";

  if (existsSync(envPath)) {
    const existing = readFileSync(envPath, "utf8");
    const match    = existing.match(/^GUARDIAN_API_KEY=(.+)$/m);
    if (match?.[1] && match[1] !== "your-secret-api-key-here") {
      apiKey = match[1];
      ok(`Reusing existing API key from ${envPath}`);
    }
  }

  if (!apiKey) {
    apiKey = randomBytes(32).toString("hex");
    ok(`Generated new API key`);
  }

  // ── Step 4: Write config files ────────────────────────────────────────────

  step(4, "Writing configuration");

  writeFileSync(envPath, makeEnvFile(apiKey));
  ok(`Created .env`);

  const composePath = join(installDir, "docker-compose.yml");
  writeFileSync(composePath, makeDockerCompose(3000));
  ok(`Created docker-compose.yml`);

  // ── Step 5: Start containers ──────────────────────────────────────────────

  step(5, "Starting containers");

  info("Pulling images and starting services (this may take a minute)…");
  const started = run(`docker compose -f "${composePath}" --env-file "${envPath}" up -d`);

  if (!started) {
    err("docker compose up failed. Check the output above for details.");
    process.exit(1);
  }

  ok("Containers started");

  // ── Done ──────────────────────────────────────────────────────────────────

  console.log(`
${c.bold}${c.green}  ✅  Frontend Guardian is running!${c.reset}

  ${c.bold}Dashboard${c.reset}   →  ${c.cyan}http://localhost:3000${c.reset}
  ${c.bold}API server${c.reset}  →  ${c.cyan}http://localhost:4000${c.reset}

${c.bold}  Add to your app:${c.reset}

  ${c.grey}# Install the SDK${c.reset}
  npm install frontend-guardian

  ${c.grey}// In your app's entry point (main.ts / index.tsx / App.tsx)${c.reset}
  ${c.cyan}import${c.reset} { initFrontendGuardian } ${c.cyan}from${c.reset} ${c.green}"frontend-guardian"${c.reset};

  initFrontendGuardian({
    apiUrl:      ${c.green}"http://localhost:4000"${c.reset},
    apiKey:      ${c.green}"${apiKey.slice(0, 8)}…"${c.reset},  ${c.grey}// your full key is in ${envPath}${c.reset}
    environment: ${c.green}"production"${c.reset},
  });

${c.bold}  To stop:${c.reset}   ${c.grey}docker compose -f ${composePath} down${c.reset}
${c.bold}  To update:${c.reset} ${c.grey}docker compose -f ${composePath} pull && docker compose -f ${composePath} up -d${c.reset}
`);
}

main().catch((e) => {
  err(String(e));
  process.exit(1);
});
